CREATE DATABASE IF NOT EXISTS `db` ;
USE `db` ;

CREATE TABLE IF NOT EXISTS `db`.`velha` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `jogadorX` VARCHAR(30) NULL DEFAULT NULL,
  `jogadorO` VARCHAR(30) NULL DEFAULT NULL,
  `jogadas` VARCHAR(30) NULL DEFAULT NULL,
  `img` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

